//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UCL.Models.Data
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Programme
    {
        public int ProgrammeId { get; set; }
        [Required]
        public string ProgrammeTitle { get; set; }
        [Required]
        public string ProgrammeDescription { get; set; }
        [Required]
        public string ProgrammeFee { get; set; }
        [Required(ErrorMessage = "Selecting a faculty is required.")]
        public int FacultyId { get; set; }
    
        public virtual Faculty Faculty { get; set; }
    }
}
